title: "The Blueprint for Next-Generation Software Engineering: Inside the AI4SWEng Architecture"
author: "University of Reading"
description: "Discover how the AI4SWEng framework is redefining software engineering. This article explores the AI-SysDev Platform, Key Innovation Outputs (KIOs), and an orchestrated, human-in-the-loop approach that makes AI-driven development faster, auditable, and enterprise-ready. Learn how modern software engineering is shifting from writing code to orchestrating intelligent systems." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "atta.badii@reading.ac.uk"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
